export interface ShopItem {
  id: string;
  name: string;
  price: number;
  category: string;
  description: string;
  emoji: string;
}

export const shopItems: ShopItem[] = [
  {
    id: "raffaello",
    name: "Raffaello Chocolates",
    price: 60,
    category: "Treats",
    description: "Premium almond and coconut confections",
    emoji: "🍬",
  },
  {
    id: "ferrero",
    name: "Ferrero Rocher",
    price: 85,
    category: "Treats",
    description: "Gold-wrapped hazelnut milk chocolates",
    emoji: "🍫",
  },
  {
    id: "jewelry",
    name: "Premium Jewelry",
    price: 350,
    category: "Gifts",
    description: "Elegant necklace or bracelet in a luxury box",
    emoji: "💍",
  },
  {
    id: "wine",
    name: "Premium Wine",
    price: 180,
    category: "Drinks",
    description: "Carefully selected vintage for romantic evenings",
    emoji: "🍷",
  },
  {
    id: "vals-card",
    name: "Val's Day Card",
    price: 35,
    category: "Personal",
    description: "Handcrafted romantic card with your message",
    emoji: "💌",
  },
  {
    id: "wallet",
    name: "Designer Wallet",
    price: 220,
    category: "Gifts",
    description: "Genuine leather wallet in a sleek design",
    emoji: "👛",
  },
  {
    id: "custom-slippers",
    name: "Custom Slippers",
    price: 125,
    category: "Gifts",
    description: "Comfortable plush slippers with custom embroidery",
    emoji: "🩴",
  },
  {
    id: "nike-slides",
    name: "Nike Slides",
    price: 380,
    category: "Gifts",
    description: "Authentic Nike comfort slides for him",
    emoji: "👟",
  },
  {
    id: "handwritten-letter",
    name: "Handwritten Letter",
    price: 50,
    category: "Personal",
    description: "Calligraphy letter on premium parchment paper",
    emoji: "✉️",
  },
  {
    id: "designer-shirt",
    name: "Designer Shirt",
    price: 280,
    category: "Gifts",
    description: "High-quality cotton shirt in his size",
    emoji: "👔",
  },
  {
    id: "db-perfume",
    name: "David Beckham Perfume",
    price: 1100,
    category: "Gifts",
    description: "Signature designer fragrance by David Beckham",
    emoji: "🧪",
  },
  {
    id: "food-basket",
    name: "Luxury Food Basket",
    price: 450,
    category: "Treats",
    description: "Gourmet selection of snacks, fruits and delicacies",
    emoji: "🧺",
  },
  {
    id: "oxford-shoes",
    name: "Oxford Shoes",
    price: 850,
    category: "Gifts",
    description: "Classic handcrafted leather Oxford shoes",
    emoji: "👞",
  },
  {
    id: "fuel-coupons",
    name: "Fuel Coupons",
    price: 200,
    category: "Gifts",
    description: "Prepaid fuel vouchers for easy mobility",
    emoji: "⛽",
  },
  {
    id: "room-diffuser",
    name: "Room Diffuser",
    price: 95,
    category: "Decor",
    description: "Essential oil diffuser for a romantic atmosphere",
    emoji: "💨",
  },
  {
    id: "car-freshener",
    name: "Car Freshener",
    price: 45,
    category: "Decor",
    description: "Premium scent for his vehicle",
    emoji: "🌲",
  },
  {
    id: "birkenstocks",
    name: "Birkenstocks",
    price: 550,
    category: "Gifts",
    description: "Authentic comfort footwear by Birkenstock",
    emoji: "🩴",
  },
  {
    id: "body-products",
    name: "Body Care Set",
    price: 180,
    category: "Personal",
    description: "Luxury grooming and body care collection",
    emoji: "🧴",
  },
  {
    id: "custom-jersey",
    name: "Custom Jersey",
    price: 320,
    category: "Gifts",
    description: "His favorite team's jersey with custom name",
    emoji: "👕",
  },
  {
    id: "grooming-products",
    name: "Grooming Kit",
    price: 250,
    category: "Personal",
    description: "Complete beard and face care grooming set",
    emoji: "🪒",
  },
];

export const baseServices = [
  {
    id: "room-aesthetics",
    name: "Room Aesthetics",
    description: "Transform any space into a breathtaking romantic scene with curated decor, lighting and ambiance.",
    emoji: "🛏️",
    color: "from-[#F2B8C6]/20 to-[#9b87f5]/10",
  },
  {
    id: "surprise-package",
    name: "Surprise Package",
    description: "A fully curated secret experience delivered to your loved one — we handle everything.",
    emoji: "🎁",
    color: "from-[#D4AF37]/20 to-[#F2B8C6]/10",
  },
  {
    id: "custom-setup",
    name: "Custom Setup",
    description: "Build your dream setup from scratch. Mix and match items exactly the way you envision it.",
    emoji: "✨",
    color: "from-[#9b87f5]/20 to-[#F2B8C6]/10",
  },
];
